server:
  port: 8090
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/perm_template?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: WEB-INF/**

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/*.xml

mybatis-plus:
  # 扫描 mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    db-config.logic-delete-value: 1 # # 逻辑已删除值(默认为 1)
    logic-not-delete-value: 0 # 逻辑未删除值（默认 0）

logging:
  level:
    work.gg3083.template.mapper : debug
